# Generated by Django 3.0.6 on 2020-05-14 19:10

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goco_sqt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_hpbx',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product_hpbx',
            name='setup',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=8, null=True),
        ),
    ]
