# Generated by Django 3.0.6 on 2020-05-15 01:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goco_sqt', '0003_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='price_1yr_2yr',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='price_3yr',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='price_nt',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=7, null=True),
        ),
    ]
