# Generated by Django 3.0.7 on 2020-07-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goco_sqt', '0004_auto_20200515_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lease',
        ),
    ]
