# Generated by Django 3.0.7 on 2020-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goco_sqt', '0005_remove_customer_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lease',
            field=models.CharField(choices=[('3', '36 Months (3 Year)'), ('5', '60 Months (5 Year)')], default='3', max_length=3),
        ),
    ]
